[package]
name = "sfo-split"
version = "0.1.2"
edition = "2021"
license-file = "LICENSE"
repository = "https://github.com/wugren/sfo-split.git"
description = "Implement splittable object"

[dependencies]
